### PR TITLE
Upgrade gems

### PR DESCRIPTION
**Pull request by larouxn**
Just some more gem upgrades, all minor.

### CODE REVIEW

**Comment by robwhitaker** [comment]
Running into this while trying to build on the review branch. Not sure if it's a new issue introduced by the review or something we just didn't notice before yet.

```
Setting up the database... 
rake aborted!              
LoadError: cannot load such file -- sinatra/activerecord/rake/activerecord_6
/nix/store/7fbxg9ri91fgzhmmlvsswlf4rxabagn6-ruby2.6.1-sinatra-activerecord-2.0.13/lib/ruby/gems/2.6.0/gems/sinatra-activerecord-2.0.13/lib/sinatra/activerecord/rake.rb:2:in `require'     
/nix/store/7fbxg9ri91fgzhmmlvsswlf4rxabagn6-ruby2.6.1-sinatra-activerecord-2.0.13/lib/ruby/gems/2.6.0/gems/sinatra-activerecord-2.0.13/lib/sinatra/activerecord/rake.rb:2:in `<top (required)>'
/home/rhit/projects/mmp/gem-updates/mmp-website/Rakefile:1:in `require'
/home/rhit/projects/mmp/gem-updates/mmp-website/Rakefile:1:in `<top (required)>'
/nix/store/ni5q0sjgvivvlghyrdf8yylmx7lkrjh5-mmp-website/lib/ruby/gems/2.6.0/gems/rake-12.3.3/exe/rake:27:in `<top (required)>'
(See full trace by running task with --trace)
```

**Comment by larouxn** [comment]
Ah, I see. I'll look into that later today if I can.

**Comment by larouxn** [comment]
Actually, I think I figured out the issue already. We need to bump one other gem to add support for Rails 6.

Likely broke the task with the last bump. Should be fixed in this PR once we grab:
https://github.com/janko/sinatra-activerecord/releases/tag/v2.0.14

**Comment by larouxn** [comment]
I have bumped `sinatra-activerecord` to `v2.0.14` as is required. Everything works now. :)
wow
wow2

**Review by robwhitaker — APPROVED** [review]
Looks good now. Merge away!

**Pull request merged**
