### PR TITLE
Haskell CSS - replaced all CSS with Haskell Clay

### PR DESCRIPTION
**Pull request by robwhitaker**
Since all the CSS has been rewritten in Haskell, a full cross-browser test (Chrome, FF, Safari, IE, Edge, etc. + mobile) is needed before merging this into `master`. I've done a quick check on Vivaldi (basically Chrome), FF, and Edge for desktop, and they look okay at a glance. I suspect older browsers that need vendor prefixing for CSS Column-related properties (like `column-gap`, for example) might have issues.

### CODE REVIEW

**Review by larouxn — APPROVED** [review]
LGTM across Chrome, Opera, Firefox, and Opera 👌 ✨

**Comment by larouxn** [comment]
Just noticed this error on `./setup`:
`The package list for 'hackage.haskell.org' does not exist`
screen shot 2018-09-02 at 16 02 48

Have you seen this? Something wrong with the nix package list? Site still runs/looks fine.

**Comment by robwhitaker** [comment]
Yeah, I've seen it. That's a cabal warning, not a Nix warning. Same way you'd use `apt-get update` to update your listing of Ubuntu packages, you'd used `cabal update` to update your listing of Haskell/cabal packages. I assume the warning is because Nix is handling the packages, so we never bother running `cabal update`.

**Comment by larouxn** [comment]
Well, feel free to go ahead and merge. 👍

**Pull request merged**
