### PR TITLE
Upgrade to Ruby 2.6

### PR DESCRIPTION
**Pull request by larouxn**
Ruby's up to [v2.6.2](https://www.ruby-lang.org/en/news/2019/03/13/ruby-2-6-2-released/) as of mid-March. I think this is all we need to do to upgraded. Run `./upgrade-deps` with this change, no issues as far as I could tell.

### CODE REVIEW

**Comment by robwhitaker** [comment]
Unfortunately, it's not quite as straightforward as that. Any time you change `shell.nix`, you should try actually executing it with `nix-shell`. In this case, it fails with:

image

The reason for this is that we've pinned a particular set of Nix packages for easy replication of builds. Thing is, Ruby 2.6 is newer and isn't in that package set. I'm in the process of upgrading our Elm version right now (which also requires a more recent set of Nix packages), so I'll take care of this too.

**Review by robwhitaker — CHANGES_REQUESTED** [review]
Unfortunately, it's not quite as straightforward as that. Any time you change `shell.nix`, you should try actually executing it with `nix-shell`. In this case, it fails with:

image

The reason for this is that we've pinned a particular set of Nix packages for easy replication of builds. Thing is, Ruby 2.6 is newer and isn't in that package set. I'm in the process of upgrading our Elm version right now (which also requires a more recent set of Nix packages), so I'll take care of this too.

**Comment by larouxn** [comment]
Closing in favour of a later, more legitimate upgrade.

**Comment by robwhitaker** [comment]
Reopening this as upgrading the nixpkgs version is a prereq to the Elm 0.19 upgrade anyway, and tackling this now _should_ make it easier to upgrade Ruby in the future.

**Review by robwhitaker — APPROVED** [review]

**Pull request merged**
