### PR TITLE
Flexboxes should now wrap in Safari. Fixes #14.

### LINKED ISSUE #14: Footer not wrapping in Mobile Safari
Tested on an iPhone 6S Plus running iOS 9.something.
img_20160814_143331

### PR DESCRIPTION
**Pull request by robwhitaker**

### CODE REVIEW

**Comment by robwhitaker** [comment]
@larouxn - Can you check if this actually fixed Safari or not, and also make sure it didn't do anything wonky in other major browsers? Looks fine on desktop Chrome still.

**Comment by larouxn** [comment]
@robwhitaker, sure thing. I'll deploy this branch to staging and run a manual browser test against it in most major browsers.

**Comment by robwhitaker** [comment]
@larouxn - Manually added `-webkit` prefixes. Try it out now.

**Comment by larouxn** [comment]
We're golden, well, at least now in Mobile Safari! 😃 
img_20170114_212019

**Review by larouxn — APPROVED** [review]
LGTM in all browsers. 👍 🚢 it!

**Pull request merged**
